version: '3.8'
services:
  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - logs:/rails/log
      - tmp-data:/rails/tmp
      - storage-data:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  logs:
  tmp-data:
  storage-data:
